# -*- coding: utf-8 -*-
"""
/***************************************************************************
 gotoScalgo_simple
                                 A QGIS plugin
 A button that sends you straight to SCALGO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-11-07
        copyright            : (C) 2022 by Mathias Kusk
        email                : Mathias.Kusk@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Mathias Kusk'
__date__ = '2022-11-07'
__copyright__ = '(C) 2022 by Mathias Kusk'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load gotoScalgo_simple class from file gotoScalgo_simple.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gotoScalog_simple_module import gotoScalgo_simplePlugin
    return gotoScalgo_simplePlugin()
